/** @type {import('tailwindcss').Config} */
const defaultTheme = require('tailwindcss/defaultTheme');

module.exports = {
  darkMode: ["class"],
  corePlugins: {
    preflight: false,
  },
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}', 
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './containers/**/*.{js,ts,jsx,tsx,mdx}',
    // Or if using `src` directory:
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      // 1) bring back all default Tailwind colors, then...
      colors: {
        ...defaultTheme.colors,

        // 2) your nm_ custom palette
        nm_primary: '#39B277',
        nm_primary_dark: '#1D6B46',
        nm_primary_light: '#90E1BA',
        nm_primary_light_transparent: '#90E1BA33',
        nm_primary_light_2: '#EAFFF5',
        nm_primary_lighter: '#F5FFFA',
        nm_secondary: '#FFFF',
        nm_font_secondary: '#1F1F1F',
        nm_carousel_indicator: '#EAEAEA',
        nm_white: '#FFFFFF',
        nm_white_smoke: '#F7F7F7',
        nm_white_smoke_2: '#FCFEFD',
        nm_dim_gray: '#707070',
        nm_dim_gray_2: '#F1F2F3',
        nm_dark_gray: '#ABABAB',
        nm_dark_gray_2: '#292D32',
        nm_dark_gray_3: '#727272',
        nm_tertiary_gray: "#B0B0B0",
        nm_dark_gray_4: '#7A7A7A',
        nm_font_primary: '#880746',
        nm_danger_red: '#D60606',
        nm_danger_red_2: '#B20100',
        nm_light_red: '#F6BDC0',
        nm_light_red_transparent: '#F6BDC033',
        nm_red: '#DA1E28',
        nm_red_2: '#FB4141',
        nm_red_3: '#F95454',
        nm_red_4: '#FE0100',
        nm_dark_mystique_green: '#078B3E',
        nm_light_mystique_green: '#E7F9EE',
        nm_spanish_green : '#057C36',
        nm_cal_poly_pomona_green : '#045F2A',
        nm_green_cyan: '#14664B',
        nm_light_gray: '#F2F2F2',
        nm_light_gray_2: "#EEEEEE",
        nm_light_gray_3: "#B8B8B8",
        nm_light_gray_4: "#F1F2F3",
        nm_light_gray_5: "#B2B2BF",
        nm_light_gray_6: "#5E5E5E",
        nm_light_gray_7: "#DDDDDD",
        nm_light_gray_8: "#EFEFEF",
        nm_light_gray_9: "#DCDCDC",
        nm_light_gray_10: "#8E8E8E",
        nm_light_gray_11: "#6A6A6A",
        nm_light_gray_14 : '#0000001f',
        nm_light_silver: '#D6D6D6',
        nm_silver: '#C4C4C4',
        nm_light_pink: '#FDD8EA',
        nm_light_pink_2: '#FFDCEC',
        nm_border_gray: '#C4C4C4',
        nm_border_gray_2: '#D6D6D6',
        nm_dark_green: '#14664B',
        nm_light_green: '#AAEED7',
        nm_light_green_2: 'C3FFE2',
        nm_black: '#000000',
        nm_black_2: '#1A1A1A',
        nm_mask: '#00000035',
        nm_blue: '#3E68FF',
        nm_blue_2: '#3F90F0',
        nm_blue_3: "#2087FF",
        nm_dark_blue: '#292D32',
        nm_orange: '#EB9E24',
        nm_orange_2: '#FFEECE',
        nm_grey: '#E6E6E6',
        nm_grey_2: "#6E7079",
        nm_grey_3:'#B1B5C3',
        nm_neutral_grey : '#B0B0B0',
        nm_greyed_out: '#D9D9D9',
        nm_snow: '#FFF8FB',
        nm_error: '#D32F2F',
        nm_primary_text: '#3A5744',
        nm_primary_gray: '#A0D2C9',
        nm_light_green_3_transparent_10: '#31B37410',
        nm_dark_green_2: '#31B375',
        nm_dark_green_3: '#159147',
        nm_yellow: '#FFE249',
        nm_light_yellow: '#FFFDF3',
        nm_bumble_bee_yellow: '#FFFAE6',
        nm_bumble_bee_yellow_default: '#FFAB00',
        nm_bumble_bee_yellow_dark: '#ECA200',
        nm_peach: '#F9E7DC',
        nm_flamingo: '#FC88AB',
        nm_maroon: '#C23373',
        nm_mystique_green: '#0AC759',
        nm_mystique_default: "#00A143",
        nn_orange: '#C85400',
        nm_scarlet_red: "#F83849",
        nm_scarlet_pink : '#EA5088',
        nm_scarlet_red_dark:'#C50011',
        nm_scarlet_default : '#C92519',
        nm_neutral_light: "#F2F2F2",
        nm_brand: "#31B375",
        nm_bumble_bee_yellow_dark:'#ECA200',
        nm_neutral_line: "#DDDDDD",
        nm_bumble_bee_yellow_dark_2: '#FF8B00',
        nm_barbie_pink: '#E4026D',
        nm_dark_gray_5 : '#333',
        nm_light_gray_12 : '#EDEDED',
        nm_barbie_pink_1 : '#FCE6F0',
        nm_barbie_pink_2 : '#FFBFDC',
        nm_strong_red_pink : '#BB0058',
        nm_light_gray_13 : '#D3D3D3',
        nm_blue_4 : '#02AEE4',
        nm_foundation_red : '#F1C9DA',
        nm_denim_diva_blue_dark : "#0198C7",
        nm_dark_pink : '#BB0058',
        nm_scarlet_red_dark : '#C50011',
        nm_neon_green : '#AFFF00',
        nm_error_state : '#C50011',
        nm_neutral_black: '#1A1A1A',
        nm_neutral_secondary: "#6A6A6A",
        nm_text_primary: '#1F1F1F',
        nm_light_mystique_green_2:'#EFF8E6',
        nm_mystique_green_dark:'#5EBB06',
        nm_pale_orange:'#FFE2BF',
        nm_light_orange:'#FFF1E0',
        nm_light_orange_2:'#FFF1E1',
        nm_ginger_spice_orange_default:'#EC6300',
        nm_green_sale:'#7AB200',
        nm_light_red_1 : '#FFE6E6',
        nm_barbie_pink_3 : '#FF4EA2',
        nm_bogo_timer:'#81BA05',
        nm_grey_4 : '#D1D3D4',
        nm_grey_light:'#f5f5f5',
        nm_raspberry_red:'#E50C50',
        nm_jade_green:'#1EB473',
        nm_crimson_red:'#C61219',
        nm_valentine_bg:'#FFF0F0',
        nm_dark_green:'#1EB473',
        nm_pink_lavender : '#D8BEEA',
        nm_pink_new:'#E54A7D',
        nm_grey_light_bg:'#E0E0E0',
        nm_white_2 : '#F9F9F9',
        nm_bogo_orange : '#FC6827',
        nm_dark_yellow:'#F1DF01',
        
        // 3) your existing shadcn/ui vars still in extend
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },

      fontFamily: {
        sans: ['var(--font-jakarta)'],
        balgin: ['var(--font-balgin-display-semi-bold)'],
        balgin_regular: ['var(--font-balgin-regular)'],
      },

      boxShadow: {
        pdpHeader: '0px 4px 16px 0px rgba(26, 26, 26, 0.08)',
        categoryBottomSheet: '0px -8px 24px 0px rgba(26, 26, 26, 0.10)',
        recommendedCards: '2.395px 2.395px 0px 0px #000',
      },

      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },

      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },

      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
